import postgres from 'postgres';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
};

const guestStatements = [
  `CREATE TABLE IF NOT EXISTS public.guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    city TEXT DEFAULT '',
    table_number TEXT DEFAULT '',
    status TEXT DEFAULT 'Silver',
    lat FLOAT DEFAULT 55.0,
    lng FLOAT DEFAULT 37.0,
    is_arrived BOOLEAN DEFAULT FALSE,
    payment INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `ALTER TABLE public.guests ALTER COLUMN id SET GENERATED BY DEFAULT`,
  `ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY`,
  `DROP POLICY IF EXISTS "Public access" ON public.guests`,
  `CREATE POLICY "Public access" ON public.guests
    FOR ALL
    USING (true)
    WITH CHECK (true)`,
  `DO $$
  BEGIN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.guests;
    EXCEPTION
      WHEN duplicate_object THEN NULL;
      WHEN duplicate_table THEN NULL;
    END;
  END;
  $$`,
];

function jsonResponse(body: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      'Content-Type': 'application/json; charset=utf-8',
    },
  });
}

export default {
  async fetch(request: Request) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: corsHeaders });
    }

    if (request.method !== 'GET' && request.method !== 'POST') {
      return jsonResponse({ error: 'Method not allowed' }, 405);
    }

    const connectionString = Deno.env.get('SUPABASE_DB_URL');
    if (!connectionString) {
      return jsonResponse({ error: 'SUPABASE_DB_URL is not set' }, 500);
    }

    const sql = postgres(connectionString, { prepare: false });

    try {
      for (const statement of guestStatements) {
        await sql.unsafe(statement);
      }

      return jsonResponse({
        ok: true,
        message: 'Database initialized',
        tables: ['guests'],
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return jsonResponse({ error: message }, 500);
    } finally {
      await sql.end({ timeout: 5 });
    }
  },
};
